version: '3.2'

services:
   db:
      image: mysql:8.0
      container_name: appsDB
      restart: always
      ports:
       - '6603:3306'
      environment:
        MYSQL_ROOT_PASSWORD: 1352

   apl:
      depends_on:
       - db
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      restart: always
      ports:
       - '8080:80'
      environment:
        PMA_HOST: db

   appp:
      build:
         context: ./
         dockerfile: Dockerfile
      container_name: app
      ports:
       - "4000:4000"
    
      command: "/app"


   
        